language: objective-c
osx_image: xcode9.2
script: xcodebuild clean && xcodebuild build test -project LogViewer.xcodeproj -scheme LogViewer -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2'
after_success:
- bash <(curl -s https://codecov.io/bash)
