language: objective-c
osx_image: xcode9.2
script: xcodebuild clean && xcodebuild build -project LogViewer.xcodeproj -scheme LogViewer -sdk iphonesimulator
after_success:
- bash <(curl -s https://codecov.io/bash)
